apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-startup-crac-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-startup-crac-demo
  template:
    metadata:
      labels:
        app: spring-boot-startup-crac-demo
    spec:
      containers:
      - name: spring-boot-startup-crac-demo
        image: ghcr.io/majguo/spring-boot-startup-crac-demo:checkpoint
        imagePullPolicy: Always
        securityContext:
          privileged: false
          capabilities:
            add:
            - CHECKPOINT_RESTORE
            drop:
            - ALL
