apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: spring-boot-demo
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-startup-crac-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: spring-boot-startup-crac-demo
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-warmup-crac-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: spring-boot-warmup-crac-demo
