FROM ubuntu:23.04

ARG CRAC_JDK_URL

ENV JAVA_HOME /opt/jdk
ENV PATH $JAVA_HOME/bin:$PATH
ENV CRAC_FILES_DIR /opt/crac-files

RUN apt-get -y update
RUN apt-get -y install curl siege

ADD $CRAC_JDK_URL $JAVA_HOME/openjdk.tar.gz
RUN tar --extract --file $JAVA_HOME/openjdk.tar.gz --directory "$JAVA_HOME" --strip-components 1; rm $JAVA_HOME/openjdk.tar.gz;
RUN mkdir -p /opt/app
COPY target/spring-boot-crac-demo-1.0.0-SNAPSHOT.jar /opt/app/spring-boot-crac-demo-1.0.0-SNAPSHOT.jar
COPY src/scripts/entrypoint-warmup.sh /opt/app/entrypoint-warmup.sh
COPY target/readiness.sh /opt/app/readiness.sh

ENTRYPOINT /opt/app/entrypoint-warmup.sh
