apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-boot-warmup-crac-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-boot-warmup-crac-demo
  annotations:
    autoscaling.knative.dev/min-scale: "0"
spec:
  image: ghcr.io/majguo/spring-boot-warmup-crac-demo:checkpoint
